### PR TITLE
avoid problems with short args

### PR DESCRIPTION
**Pull request by inorton**
Fix JENKINS-35422 issue that occurs when valgrind is called with short command line arguments.

### CODE REVIEW

**Comment by winotu** [comment]
@maintainers When can we expect merge of this PR ?

**Comment by inorton** [comment]
@eXistence @adriaan42 is development on this plugin still alive?

**Comment by adriaan42** [comment]
I hope the plugin is still alive ;-)
Thanks for your patch, I would love to merge it, but I don't have write access myself...

**Comment by inorton** [comment]
Hiya, I'm still keen for my little change to live on! :)

**Comment by inorton** [comment]
*prod* 👍

**Comment by eXistence** [comment]
finally merged and released with version 0.28, thx for contributing!

**Pull request closed without merging**
