### PR TITLE
Helgrind Support

### PR DESCRIPTION
**Pull request by adriaan42**
This series of patches extends the Valgrind plugin to support Helgrind (in addition to Memcheck).
It addresses https://issues.jenkins-ci.org/browse/JENKINS-25776

### CODE REVIEW

**Comment by eXistence** [comment]
Thx for your pull request! I am pretty busy right now, so i hadn't had the time to take a closer look at your changes. I hope to be able to do that soon. Thx for your patience :)

**Comment by adriaan42** [comment]
Just a quick follow-up... did you have a chance to review my proposal yet?
Thanks!

**Comment by bufferoverflow** [comment]
I've tested this helgrind extension, :+1:

**Comment by eXistence** [comment]
I am a bit worried about the readability of the graph, but everything alse looks pretty good. Thx for the patch!

**Comment by lucmann** [comment]
> I've tested this helgrind extension, 👍

Hi, Roger @bufferoverflow
I have had Valgrind plugin working only with memcheck tool on my jenkins pipeline. I have no idea how to enable this extension at the same time.  I try the code below, but not working.

Valgrind plugin version: 0.28
Jenkins ver.2.164.3

```
stage('Valgrind') {
   steps {
      runValgrind(
          .....
          tool: [$class: 'ValgrindToolMemcheck',
              leakCheckLevel: 'full',
              showReachable: true,
              trackOrigins: true,
              undefinedValueErrors: true
          ],
              [$class: 'ValgrindToolHelgrind',
              historyLevel: 'full'
          ],
          .....
      )
   }
}
```
I know that parameter `tool` is a type of nested choice of objects, but I don't know what exactly its syntax  is in Jenkinsfile.  

Thanks!

**Pull request merged**
