### PR TITLE
Add jenkins  pipeline compatibility

### PR DESCRIPTION
**Pull request by Wulkop**
Fix issue: [34981](https://issues.jenkins-ci.org/browse/JENKINS-34981)
Refractor occurences of AbstractBuild and AbstractProject to Run and Job.
Add custom pipeline step.
Modified ValgrindPublisher to implement SimpleBuildStep to create a metastep.

### CODE REVIEW

**Comment by frznlogic** [comment]
Hi, I'm interested in these changes and hoping they get pulled soon. If there's any testing I can do or otherwise to help out, I'm here;)

**Comment by eXistence** [comment]
sorry for the late answer, i will look into it within the next few days :)

**Comment by cyrilschmitt** [comment]
Hello,

We tested it and it works, we use this build until it gets pulled.

**Comment by lgawel-cayan** [comment]
Hi @Wulkop when are you planning on pulling those changes into master and getting an official release of the plugin? We've been waiting for this fix for a while now

**Comment by Wulkop** [comment]
Hi @lgawel-cayan,
sorry if I get you wrong, but I am not able to approve this pull request. The problem is that there are still some warnings when running findbugs target in Jenkins. But I don't think that these warnings are related to the changes I made. They also occure when running findbugs on the master branch of the official repo.

**Comment by roy-van-de-korput** [comment]
Any update on what the next step would be to get this into master?

**Comment by pyssling** [comment]
@eXistence @Wulkop anything I can do to help? I had a look at the findbugs output, and it seems like pretty simple stuff to fix, most of it at least...

Having valgrind reporting from pipeline would make things a lot simpler for us.

**Comment by SamRaina** [comment]
Checking on behalf of a customer who had placed a request for this to see if this will be possible and if so, what is the timeline? Thanks.

**Comment by eXistence** [comment]
i will try to make merge the PR today and release a new version.

**Comment by dimagr-arm** [comment]
Any update on this?
How can I help to make it happen?

**Comment by amarlier** [comment]
Hello

any news on the pull request? We would like to use it asap, because the workaround of freestyle project is not really nice.

thks
A

**Comment by DoDoENT** [comment]
Any news about merging this PR?

**Comment by zeton3** [comment]
What's the sense to investigate and fix errors then don't release it?

**Comment by adpoint72** [comment]
What's the latest on this?

**Comment by Zaccc123** [comment]
Hi, any plan to fix and merge this? We have a few project that uses valgrind in freestyle job and likes to move it to pipeline job. Would really appreciate if it can be merged into the official plugin.

**Comment by martukas** [comment]
I'll pitch in with the same. Anything I, nay, we can do to help? I have an army of programmers here at [ESS](https://github.com/ess-dmsc/) with a ton of projects that need this. Can I bribe you? Or is there anything you're afraid of? :)

**Comment by truh** [comment]
@martukas you could try to find out whether @eXistence is still interested in maintaining this plugin and adopt it if he isn't.

**Comment by Lakshmipathi** [comment]
+1 This will be very useful pipeline plugin, I hope it gets merged and maintained.

**Comment by lexxxel** [comment]
+1 bumb this PR it would be very nice if this gets fixed somehow

**Comment by shekharhimanshu** [comment]
Is there a way to use this PR branch (`Wulkop:master`) instead of `jenkinsci:master`?

I tried using `Wulkop:master`'s valgrind-plugin as a Global shared library as mentioned [here](https://jenkins.io/doc/book/pipeline/shared-libraries/#global-shared-libraries).

Jenkinsfile:
```
#!groovy

@Library('valgrind-plugin')
import org.jenkinsci.plugins.valgrind.*
```

But job fails with following error:
```
Loading library valgrind-plugin@master
Attempting to resolve master from remote references...
 > git --version # timeout=10
 > git ls-remote -h -t https://github.com/Wulkop/valgrind-plugin.git # timeout=10
Found match: refs/heads/master revision 7741c1012a156a289b75d399a632d8eccb33457d
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/Wulkop/valgrind-plugin.git # timeout=10
Fetching without tags
Fetching upstream changes from https://github.com/Wulkop/valgrind-plugin.git
 > git --version # timeout=10
 > git fetch --no-tags --progress https://github.com/Wulkop/valgrind-plugin.git +refs/heads/*:refs/remotes/origin/*
Checking out Revision 7741c1012a156a289b75d399a632d8eccb33457d (master)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 7741c1012a156a289b75d399a632d8eccb33457d
Commit message: "Update dependencies to be compatible with newer test procedure"
 > git rev-list --no-walk 7741c1012a156a289b75d399a632d8eccb33457d # timeout=10
ERROR: Library valgrind-plugin expected to contain at least one of src or vars directories
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
WorkflowScript: Loading libraries failed

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:310)
	at org.codehaus.groovy.control.CompilationUnit.applyToPrimaryClassNodes(CompilationUnit.java:1085)
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:603)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:581)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:558)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:298)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:268)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:688)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:700)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.doParse(CpsGroovyShell.java:133)
	at org.jenkinsci.plugins.workflow.cps.CpsGroovyShell.reparse(CpsGroovyShell.java:127)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.parseScript(CpsFlowExecution.java:557)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.start(CpsFlowExecution.java:518)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:290)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:421)
Finished: FAILURE
```

Error says, `Library valgrind-plugin expected to contain at least one of src or vars directories` but when checked `valgrind-plugin` does contain `src` directory.

**Comment by jameswtelfer** [comment]
@shekharhimanshu Yes, you have to check out the branch from git, build it and then upload the built plugin package via the Advanced tab of the Manage Plugins page in the Jenkins Admin area.

**Comment by shekharhimanshu** [comment]
Thanks @jameswtelfer. Will try that.

**Comment by shekharhimanshu** [comment]
Workaround suggested by @jameswtelfer worked. Thanks!
For anyone trying the same, here's how to use inside pipeline step,

```
step([$class: 'ValgrindPublisher',
    pattern: 'build/reports/valgrind/*.xml',
    failBuildOnMissingReports: false,
    failBuildOnInvalidReports: false,
    publishResultsForAbortedBuilds: false,
    publishResultsForFailedBuilds: false,
    failThresholdInvalidReadWrite: '',
    unstableThresholdInvalidReadWrite: '',
    failThresholdDefinitelyLost: '',
    unstableThresholdDefinitelyLost: '',
    failThresholdTotal: '',
    unstableThresholdTotal: '0'
])
```

**Comment by eXistence** [comment]
finally merged and released with version 0.28, thx for contributing!

**Pull request closed without merging**
